### PR TITLE
[jenkins] fix: fail to decode line on Windows

### PR DESCRIPTION
**Pull request by Wayonb**
problem: building catapult deps fails on Windows due to an invalid UTF-8 character
solution: add exception handling

### CODE REVIEW

**Comment by Jaguar0625** [comment]
what is source of `invalid UTF-8 character` ?

**Comment by Wayonb** [comment]
> what is source of `invalid UTF-8 character` ?

It happens when build the mongocxx

**Comment by Jaguar0625** [comment]
is it possible to conditionally enable this new handling only for mongocxx by adding another paramter?

**Comment by Wayonb** [comment]
> is it possible to conditionally enable this new handling only for mongocxx by adding another parameter?

The best I can do is enable exception handling only when building the catapult dependencies. This is one command.

**Review by Jaguar0625 — APPROVED** [review]
👍

**Pull request merged**
