### PR TITLE
[client/catapult] : msvc warnings

### PR DESCRIPTION
**Pull request by AndreaLanfranchi**
This PR amends some warnings from MSVC toolchain as well removing some warning suppression code which is actually not needed anymore.

### CODE REVIEW

**Comment by Jaguar0625** [comment]
what version of msvc is reporting these errors?

@Wayonb - are there any issues with any msvc CI builds?

**Comment by AndreaLanfranchi** [comment]
> what version of msvc is reporting these errors?

Actually none. For example [this one](https://github.com/symbol/symbol/pull/1137/commits/f1bc24b2286239d4ce98810ba1d9956935f09c74) is clearly a leftover from some previous implementation. (There's no more shadowing)

The purpose of this PR is to **remove** silencers that are actually not needed.

**Comment by Wayonb** [comment]
> @Wayonb - are there any issues with any msvc CI builds?

The Windows builds are currently passing.
Are these related to the Debug build? 🤔

**Comment by AndreaLanfranchi** [comment]
> The Windows builds are currently passing. Are these related to the Debug build? 🤔

Of course they are ... but the point of this PR is to **remove** silencers that are actually not needed.
Leaving them in place could lead to the unwanted situation when, maybe due to future modifications, the warning effectively triggers but we wouldn't know as it's already silenced.

**Review by Wayonb — APPROVED** [review]
👍🏾

**Comment by AndreaLanfranchi** [comment]
Thank you for the approval.
Either of you must merge though as I don't have write permissions.

**Pull request merged**
